name: flutter_assignment
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  http: ^1.1.0
  infinite_scroll_pagination: ^4.0.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  logger: ^2.0.2+1
  retrofit: ^4.0.3
  shimmer: ^3.0.0
  url_launcher: ^6.1.14


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^8.0.6
  build_runner: ^2.4.7


flutter:
  uses-material-design: true